# https://docs.docker.com/build/ci/github-actions/github-builder/build/
name: Build and publish Docker image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of the image
        required: true
        type: string
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize, edited]
    branches: [master]
    paths:
      - .github/workflows/docker-image.yaml
      - Dockerfile
      - pyproject.toml
      - uv.lock

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      packages: write
      contents: read
      id-token: write
    with:
      output: image
      push: ${{ github.event_name != 'pull_request' }}
      platforms: linux/amd64,linux/arm64
      meta-images: |
        ${{ vars.DOCKERHUB_REPO }}
        ghcr.io/${{ github.repository }}
      meta-tags: |
        type=ref,event=pr
        type=semver,pattern={{raw}}
        type=raw,value=${{ inputs.tag }},enable=${{ github.event_name == 'workflow_dispatch' }}
        type=raw,value=latest,enable={{is_default_branch}}
      sbom: true
      set-meta-labels: true
    secrets:
      registry-auths: |
        - registry: docker.io
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        - registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

  attest:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      attestations: write
    steps:
      - name: Generate artifact attestation (Docker Hub)
        uses: actions/attest@v4
        with:
          subject-name: index.docker.io/${{ vars.DOCKERHUB_REPO }}
          subject-digest: ${{ needs.build.outputs.digest }}
          push-to-registry: true
      - name: Generate artifact attestation (GitHub)
        uses: actions/attest@v4
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ needs.build.outputs.digest }}
          push-to-registry: true
